### ISSUE TITLE
Missing dependency for TensorFlow

### ISSUE THREAD

**Issue by luheng** [mikelewis0/EasySRL#12]
It seems that InputReader.TensorFlowInputReader requires some additional dependencies.

**Comment by mikelewis0** [comment]
Yeah, it won't work actually work until Kenton's library is released. The library is aimed at GPU parsing, so I don't think you need it at the moment.

Hopefully everything still compiles ok, though?

**Comment by luheng** [comment]
Yes, if I comment out the related code.

**Comment by mikelewis0** [comment]
Hmm - what error do you get otherwise?

**Comment by luheng** [comment]
The compile complains about the import:
import edu.uw.Taggerflow;
import edu.uw.TaggingResult;

**Comment by mikelewis0** [comment]
There's a file called taggerflow.jar in the lib folder. You may need to update your project settings so that that's on the Java build path.

**Comment by luheng** [comment]
Ok, it compiles now. thanks a lot!
