### ISSUE TITLE
Two events conflated to a single variable

### ISSUE THREAD

**Issue by nschneid** [mikelewis0/EasySRL#5]
For ["Mary ate pie, John reported yesterday"](http://lil.cs.washington.edu/easysrl/demo.cgi?sentence=Mary+ate+pie%2C+John+reported+yesterday.), the 2nd CCG parse looks correct, but in the semantics there is a single event variable for both 'ate' and 'reported'. Is this the intended behavior?

**Comment by mikelewis0** [comment]
Thanks - should be fixed now. Any other feedback is much appreciated!
