### ISSUE TITLE
Improvements to SRL output format

### ISSUE THREAD

**Issue by nschneid** [mikelewis0/EasySRL#6]
With `--outputFormat SRL` the (ideal) result for "Mary told John off yesterday for eating pie" is something like:

    told_off ARG0 Mary
    told_off ARG1 John
    told_off TMP yesterday
    told_off CAU eating pie
    eating ARG0 John
    eating ARG1 pie

It would be nice if the format were enhanced to:

* stem the predicates as in the logical form (told_off → tell_off, eating → eat)
* include token offsets

So the improved format might look like:
  
    tell_off-1,3 ARG0 Mary-0
    tell_off-1,3 ARG1 John-2
    tell_off-1,3 TMP yesterday-4
    tell_off-1,3 CAU eating-6 pie-7
    eat-6 ARG0 John-2
    eat-6 ARG1 pie-7

**Comment by mikelewis0** [comment]
I agree - will take a look.

**Comment by nschneid** [comment]
Actually, I just realized that notation would be confusing because the offsets might be confused with PropBank frame numbers. Perhaps:

    tell_off@1,3 ARG0 Mary@0
    tell_off@1,3 ARG1 John@2
    tell_off@1,3 TMP yesterday@4
    tell_off@1,3 CAU eating@6 pie@7
    eat@6 ARG0 John@2
    eat@6 ARG1 pie@7

**Comment by mikelewis0** [comment]
OK, I've added a new output format for this. Use the option "-o srl_indices" with the latest version of the code.

Sorry for the delay, I was having too much fun with my NAACL submission...
