### ISSUE TITLE
SRL output has an empty argument

### ISSUE THREAD

**Issue by omriabnd** [mikelewis0/EasySRL#8]
For the sentence

> `` We just do n't think that the levels of profitability are as high as the projections the company has put together . ''

the output is as follows:

```
think ARG0 We
think DIS just
think NEG n't
think ARG1 that the levels of profitability are as high as the projections the company has put together
put ARG1 the projections the company has put together
put ARG0 the company
put ARG2
```

The last line has nothing in the argument, which looks like a bug.

CC: @nschneid

**Comment by mikelewis0** [comment]
Thanks! That's definitely a bug, I'll look into it.

**Comment by mikelewis0** [comment]
I couldn't reproduce this with the latest version of the code, so hopefully it's fixed.
