### ISSUE TITLE
Predicate duplicated as part of argument

### ISSUE THREAD

**Issue by omriabnd** [mikelewis0/EasySRL#9]
In some sentences, the predicate is outputted as part of the argument as well. An example below with "controlling inflation".

"In contrast to previous attempts at controlling inflation , the conversion to the real does not involve a price freeze ."

```
involve ADV In contrast to previous attempts at controlling inflation
controlling ARG0 controlling inflation
controlling ARG1 inflation
involve ARG2 the conversion to the real
involve NEG not
involve ARG1 a price freeze
```

**Comment by mikelewis0** [comment]
So I think the problem in this sentence is actually a parse error.

More generally, it deliberately includes the predicates in certain constructions. For example, in "the dog that barked", the argument of 'bark' is the full NP. Is that annoying?

**Comment by omriabnd** [comment]
I see. I guess both options make sense (in different contexts -- we were doing a lexical task..).
Thx
